name: Run tests

on:
  pull_request:
    branches: [master]
    paths:
      - src/**

  # Remove push trigger after migration is complete
  push:
    branches: [hono-migration]
    paths:
      - src/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests and generate coverage report
        run: |
          echo "### Test & Coverage Summary" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          NO_COLOR=1 npm run test:coverage >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY